import { defineCopy } from './define';

/**
 * Chrome shared by every page.
 *
 * The navigation is four destinations and one action. There are no
 * dropdowns: a menu that has to be opened to be read is a menu the visitor
 * has to work out before they can use it, and with four items there is
 * nothing to hide. What used to sit behind "Product" is now sections of the
 * homepage, so `homeSections` links into it by anchor.
 */
export const common = defineCopy({
  en: {
    skipToContent: 'Skip to content',
    homeLabel: 'Shaheen Money home',
    nav: {
      label: 'Primary',
      about: { title: 'About', desc: 'Our story and mission' },
      business: { title: 'Business', desc: 'Connectors, companies and partners' },
      blog: { title: 'Blog', desc: 'Access, trust and money across borders' },
      contact: { title: 'Contact', desc: 'Reach the right team' },
      media: 'Media & brand',
      security: 'Security',
      getApp: 'Get the app',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      menu: 'Menu',
      switchLanguage: 'اقرأ هذه الصفحة بالعربية',
      switchLanguageShort: 'العربية',
    },
    /** Sections of the homepage, linked by anchor from the footer. */
    homeSections: {
      howItWorks: 'How it works',
      cashOut: 'Cash out',
      network: 'The network',
      pricing: 'What it costs',
      faq: 'Questions',
    },
    footer: {
      product: 'Product',
      company: 'Company',
      resources: 'Resources',
      legal: 'Legal',
      nav: 'Footer',
      getApp: 'Get the app',
      accessibility: 'Accessibility',
      reportVulnerability: 'Report a vulnerability',
      privacy: 'Privacy policy',
      terms: 'Terms of service',
      cookies: 'Cookies',
      language: 'Language',
      social: 'Shaheen Money on social media',
      companyDetails: 'Company details',
      officialApps: 'Only install Shaheen Money from the App Store or Google Play links on shaheen.money.',
      rights: 'All rights reserved.',
    },
    trust: {
      label: 'Regulation and safeguarding',
      licensed: 'Licensed',
      /* The strip is one line tall. The full safeguarding paragraph lives
         on /security; this is what fits, and it still only renders when
         that fact exists. */
      selfCustody: 'Self-custodial — we never hold your money',
      protect: 'How we protect your money',
      rating: 'rating',
      reviews: 'reviews',
    },
    download: {
      label: 'Download the app',
    },
    stores: {
      group: 'Download Shaheen Money',
      ios: { kicker: 'Download on the', name: 'App Store' },
      android: { kicker: 'Get it on', name: 'Google Play' },
    },
    ui: {
      illustrative: 'Illustrative',
      illustrativeHint: 'Sample screen. Names and amounts are examples.',
      screenIos: 'The Shaheen Money app on iPhone: the home screen, with the cash balance in USDC and Add Funds, Withdraw, Send and Request.',
      screenAndroid: 'The same home screen of the Shaheen Money app on Android.',
      /* Rubber-stamp labels: the honesty layer as a designed object. */
      stamp: {
        example: 'Example',
        corridors: 'Example corridors',
        corridor: 'Example corridor',
        sourced: 'Sourced',
        note: 'Note',
      },
      email: 'Email',
      website: 'Website',
      note: 'Note',
      source: 'Source',
      asOf: 'As of',
      opensNewTab: '(opens in a new tab)',
      minRead: 'min read',
      breadcrumbs: 'Breadcrumb',
      home: 'Home',
      contentNeeded: 'Content needed',
      updated: 'Updated',
      published: 'Published',
      back: 'Back',
      download: 'Download',
    },
  },
  ar: {
    skipToContent: 'انتقل إلى المحتوى',
    homeLabel: 'الصفحة الرئيسية لشاهين موني',
    nav: {
      label: 'التنقل الرئيسي',
      about: { title: 'من نحن', desc: 'قصتنا ورسالتنا' },
      business: { title: 'الأعمال', desc: 'الموصّلون والشركات والشركاء' },
      blog: { title: 'المدونة', desc: 'عن الوصول والثقة والمال عبر الحدود' },
      contact: { title: 'تواصل معنا', desc: 'وصّل رسالتك للفريق المناسب' },
      media: 'الإعلام والهوية',
      security: 'الأمان',
      getApp: 'حمّل التطبيق',
      openMenu: 'افتح القائمة',
      closeMenu: 'أغلق القائمة',
      menu: 'القائمة',
      switchLanguage: 'Read this page in English',
      switchLanguageShort: 'English',
    },
    homeSections: {
      howItWorks: 'كيف بيشتغل',
      cashOut: 'السحب النقدي',
      network: 'الشبكة',
      pricing: 'الكلفة',
      faq: 'أسئلة',
    },
    footer: {
      product: 'المنتج',
      company: 'الشركة',
      resources: 'المصادر',
      legal: 'قانوني',
      nav: 'روابط التذييل',
      getApp: 'حمّل التطبيق',
      accessibility: 'إمكانية الوصول',
      reportVulnerability: 'الإبلاغ عن ثغرة أمنية',
      privacy: 'سياسة الخصوصية',
      terms: 'شروط الخدمة',
      cookies: 'ملفات تعريف الارتباط',
      language: 'اللغة',
      social: 'شاهين موني على وسائل التواصل',
      companyDetails: 'بيانات الشركة',
      officialApps: 'ثبّت تطبيق شاهين موني فقط من روابط App Store أو Google Play الموجودة على shaheen.money.',
      rights: 'جميع الحقوق محفوظة.',
    },
    trust: {
      label: 'الترخيص وحماية الأموال',
      licensed: 'مرخّصة',
      selfCustody: 'محفظة سيادية، إحنا ما بنحتفظ بفلوسك',
      protect: 'كيف نحمي أموالك',
      rating: 'تقييم',
      reviews: 'مراجعة',
    },
    download: {
      label: 'حمّل التطبيق',
    },
    stores: {
      group: 'حمّل تطبيق شاهين موني',
      ios: { kicker: 'تنزيل من', name: 'App Store' },
      android: { kicker: 'احصل عليه من', name: 'Google Play' },
    },
    ui: {
      illustrative: 'مثال توضيحي',
      illustrativeHint: 'شاشة نموذجية. الأسماء والمبالغ أمثلة فقط.',
      screenIos: 'تطبيق شاهين موني على آيفون: الشاشة الرئيسية، فيها الرصيد النقدي بعملة USDC وأزرار الإيداع والسحب والإرسال والطلب.',
      screenAndroid: 'الشاشة الرئيسية نفسها لتطبيق شاهين موني على أندرويد.',
      stamp: {
        example: 'مثال',
        corridors: 'أمثلة على مسارات',
        corridor: 'مسار على سبيل المثال',
        sourced: 'بمصدر موثّق',
        note: 'ملاحظة',
      },
      email: 'البريد',
      website: 'الموقع',
      note: 'ملاحظة',
      source: 'المصدر',
      asOf: 'حتى تاريخ',
      opensNewTab: '(يفتح في نافذة جديدة)',
      minRead: 'دقائق قراءة',
      breadcrumbs: 'مسار التنقل',
      home: 'الرئيسية',
      contentNeeded: 'محتوى مطلوب',
      updated: 'آخر تحديث',
      published: 'تاريخ النشر',
      back: 'رجوع',
      download: 'تنزيل',
    },
  },
});
