/**
 * Pre-computes the geography the films use, so the scenes stay plain HTML
 * with no build step and no d3 in the browser.
 *
 *   node motion/lib/make-geo.mjs
 *
 * Same data and same projections as the website (Natural Earth 1:110m via
 * world-atlas, orthographic), so the planet in the films is the planet on
 * the site — not an illustration of one.
 */
import { writeFile } from 'node:fs/promises';
import { geoGraticule, geoGraticule10, geoInterpolate, geoOrthographic, geoPath } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import land110 from 'world-atlas/land-110m.json' with { type: 'json' };
import countries110 from 'world-atlas/countries-110m.json' with { type: 'json' };

const landFeature = feature(land110, land110.objects.land);
const borderMesh = mesh(countries110, countries110.objects.countries, (a, b) => a !== b);

/* ── The hero horizon, as scenes 1 and 2 use it ─────────────────────── */
const H = { w: 1920, h: 1080, r: 1870 };
H.cx = H.w * 0.46;
H.cy = H.h + H.r * 0.79;

const horizonProjection = geoOrthographic()
  .translate([H.cx, H.cy])
  .scale(H.r)
  .rotate([-30, 25])
  .clipAngle(90)
  .precision(1.2);
const horizonPath = geoPath(horizonProjection).digits(1);

const CORRIDORS = [
  [[-0.13, 51.51], [31.24, 30.04]],
  [[13.4, 52.52], [35.5, 33.89]],
  [[2.35, 48.86], [35.93, 31.95]],
  [[46.68, 24.71], [31.24, 30.04]],
  [[55.27, 25.2], [35.93, 31.95]],
  [[13.4, 52.52], [28.98, 41.01]],
];

const horizon = {
  ...H,
  limb: horizonPath({ type: 'Sphere' }),
  graticule: horizonPath(geoGraticule().step([20, 20])()),
  land: horizonPath(landFeature),
  routes: CORRIDORS.map(([a, b]) => horizonPath({ type: 'LineString', coordinates: [a, b] })),
};

/* ── A full globe for the corridor film ─────────────────────────────── */
const G = { size: 1080, r: 500 };
const globeProjection = geoOrthographic()
  .translate([G.size / 2, G.size / 2])
  .scale(G.r)
  .rotate([-22, -38])
  .clipAngle(90)
  .precision(0.6);
const globePath = geoPath(globeProjection).digits(1);

const BERLIN = [13.4, 52.52];
const AMMAN = [35.93, 31.95];

/** The corridor, sampled so a pulse can be walked along it point by point. */
const interpolate = geoInterpolate(BERLIN, AMMAN);
const samples = 160;
const corridorPoints = [];
for (let i = 0; i <= samples; i++) {
  const p = globeProjection(interpolate(i / samples));
  if (p) corridorPoints.push([Math.round(p[0] * 10) / 10, Math.round(p[1] * 10) / 10]);
}

const globe = {
  ...G,
  sphere: globePath({ type: 'Sphere' }),
  graticule: globePath(geoGraticule10()),
  land: globePath(landFeature),
  borders: globePath(mesh(countries110, countries110.objects.countries, (a, b) => a !== b)),
  corridor: globePath({ type: 'LineString', coordinates: [BERLIN, AMMAN] }),
  corridorPoints,
  berlin: globeProjection(BERLIN).map((n) => Math.round(n * 10) / 10),
  amman: globeProjection(AMMAN).map((n) => Math.round(n * 10) / 10),
  others: [
    [-0.13, 51.51],
    [2.35, 48.86],
    [31.24, 30.04],
    [28.98, 41.01],
    [35.5, 33.89],
    [46.68, 24.71],
    [55.27, 25.2],
  ]
    .map((c) => globeProjection(c))
    .filter(Boolean)
    .map((p) => p.map((n) => Math.round(n * 10) / 10)),
};

void borderMesh;

await writeFile(
  new URL('geo.js', import.meta.url),
  `/* GENERATED by motion/lib/make-geo.mjs from Natural Earth 1:110m. Do not edit. */\n` +
    `export const HORIZON = ${JSON.stringify(horizon)};\n` +
    `export const GLOBE = ${JSON.stringify(globe)};\n`,
  'utf8',
);

const size = JSON.stringify(horizon).length + JSON.stringify(globe).length;
console.log(`geo.js: ${(size / 1024).toFixed(0)} KB (horizon + globe + ${corridorPoints.length} corridor samples)`);
