import { existsSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { Localized } from './types';
import type { Locale } from '../i18n/config';

/**
 * MEDIA AND COMPANY DOCUMENTS — what a journalist, a partner or an investor
 * can download, and the brand files they must use instead of screenshotting
 * the site.
 *
 * Two rules, both enforced below at build time rather than by discipline:
 *
 *  1. A download that 404s on a press page is worse than no download, so a
 *     file listed here must exist in public/ or the build fails.
 *  2. Nothing is described from memory: size and last-modified date are read
 *     off the file itself, so they cannot go stale.
 *
 * The company profile and the pitch deck are printed from the site's own
 * pages (src/pages/[locale]/media/) by `npm run docs`, one PDF per
 * language. A slot without a file renders a "content needed" marker in dev
 * and nothing at all in production.
 */
export interface DownloadFile {
  /** Absolute site path, e.g. '/media/shaheen-falcon-navy.svg'. */
  file: string;
  label: Localized;
  /** Filled in by the build from the file on disk. */
  format: string;
  sizeKb: number;
}

export interface DownloadSlot {
  id: string;
  title: Localized;
  description: Localized;
  /** One file per language, as site paths under public/. */
  file: Localized | null;
}

// Resolved from the working directory, not from import.meta.url: this module
// is bundled into the server output at build time, so a path relative to the
// module would point into .vercel/output (same reason src/lib/og.ts reads
// node_modules from process.cwd()).
const publicDir = join(process.cwd(), 'public');

function describe(file: string, label: Localized): DownloadFile {
  const path = join(publicDir, file);
  // A path that climbs out of public/ would describe a file the site never
  // serves, and publish a link that 404s. Fail the build instead.
  if (!file.startsWith('/') || relative(publicDir, path).startsWith('..')) {
    throw new Error(`src/data/media.ts: "${file}" must be a site-absolute path inside public/.`);
  }
  if (!existsSync(path)) {
    throw new Error(
      `src/data/media.ts lists "${file}", which is not in public/. ` +
        `Run \`npm run media\` to regenerate the brand files, or remove the entry.`,
    );
  }
  return {
    file,
    label,
    format: (file.split('.').pop() ?? '').toUpperCase(),
    sizeKb: Math.max(1, Math.round(statSync(path).size / 1024)),
  };
}

export interface BrandAsset {
  id: string;
  name: Localized;
  note: Localized;
  /** Preview background, so a white mark is never shown on white. */
  preview: 'light' | 'dark';
  /** Preview the mark inside its circle, matching what the file contains. */
  circle?: boolean;
  files: DownloadFile[];
}

/** Generated by scripts/brand/build-media.mjs from the one vector master. */
export const brandAssets: BrandAsset[] = [
  {
    id: 'mark-navy',
    name: { en: 'Falcon mark, navy', ar: 'شعار الصقر، كحلي' },
    note: {
      en: 'For light backgrounds. The default mark.',
      ar: 'للخلفيات الفاتحة، وهو الشكل الأساسي للشعار.',
    },
    preview: 'light',
    files: [
      describe('/media/shaheen-falcon-navy.svg', { en: 'Vector', ar: 'ملف متجهي' }),
      describe('/media/shaheen-falcon-navy-1024.png', { en: 'PNG 1024px', ar: 'PNG 1024 بكسل' }),
      describe('/media/shaheen-falcon-navy-512.png', { en: 'PNG 512px', ar: 'PNG 512 بكسل' }),
    ],
  },
  {
    id: 'mark-white',
    name: { en: 'Falcon mark, white', ar: 'شعار الصقر، أبيض' },
    note: {
      en: 'For navy and photographic backgrounds only.',
      ar: 'للخلفيات الكحلية والصور فقط.',
    },
    preview: 'dark',
    files: [
      describe('/media/shaheen-falcon-white.svg', { en: 'Vector', ar: 'ملف متجهي' }),
      describe('/media/shaheen-falcon-white-1024.png', { en: 'PNG 1024px', ar: 'PNG 1024 بكسل' }),
      describe('/media/shaheen-falcon-white-512.png', { en: 'PNG 512px', ar: 'PNG 512 بكسل' }),
    ],
  },
  {
    id: 'tile',
    circle: true,
    name: { en: 'Circle lockup', ar: 'الشعار داخل الدائرة' },
    note: {
      en: 'The mark in its circle, as the site and the app icon use it.',
      ar: 'الشعار داخل دائرته، كما يستخدمه الموقع وأيقونة التطبيق.',
    },
    preview: 'light',
    files: [
      describe('/media/shaheen-falcon-tile-navy.svg', { en: 'Navy circle', ar: 'دائرة كحلية' }),
      describe('/media/shaheen-falcon-tile-white.svg', { en: 'White circle', ar: 'دائرة بيضاء' }),
      describe('/icon-512.png', { en: 'App icon, PNG 512px', ar: 'أيقونة التطبيق، PNG 512 بكسل' }),
    ],
  },
];

/**
 * The company's documents, one PDF per language. The profile and the deck
 * are generated (`npm run build && npm run docs && npm run build`); the
 * brand guidelines are still to come.
 */
export const documentSlots: DownloadSlot[] = [
  {
    id: 'pitch-deck',
    title: { en: 'Pitch deck', ar: 'العرض التقديمي' },
    description: {
      en: 'Eleven slides: the problem, the app, the Connector network, pricing, trust and the team.',
      ar: 'إحدى عشرة شريحة: المشكلة، والتطبيق، وشبكة الموصّلين، والأسعار، والثقة، والفريق.',
    },
    file: { en: '/media/shaheen-money-pitch-deck-en.pdf', ar: '/media/shaheen-money-pitch-deck-ar.pdf' },
  },
  {
    id: 'company-profile',
    title: { en: 'Company profile', ar: 'الملف التعريفي للشركة' },
    description: {
      en: 'Five pages: who we are, what the app does, what it costs, and how to reach us.',
      ar: 'خمس صفحات: من نحن، وماذا يفعل التطبيق، وكم يكلّف، وكيف تتواصل معنا.',
    },
    file: { en: '/media/shaheen-money-company-profile-en.pdf', ar: '/media/shaheen-money-company-profile-ar.pdf' },
  },
  {
    id: 'brand-guidelines',
    title: { en: 'Brand guidelines', ar: 'دليل الهوية البصرية' },
    description: {
      en: 'Clear space, minimum sizes, colour and typography in full.',
      ar: 'المساحة الحرة والأحجام الدنيا والألوان والخطوط بالتفصيل.',
    },
    file: null,
  },
];

/** Both languages' files are checked at build time, whichever page asks. */
const resolved = documentSlots.map((slot) => ({
  ...slot,
  downloads: slot.file ? { en: describe(slot.file.en, slot.title), ar: describe(slot.file.ar, slot.title) } : null,
}));

/** The documents a page in this language links to. */
export const documentsFor = (locale: Locale) =>
  resolved.map(({ downloads, ...slot }) => ({ ...slot, download: downloads ? downloads[locale] : null }));

/**
 * The app as it is: the owner's renders of the home screen, cropped to the
 * screen (the same images the site shows, src/assets/app/).
 */
export const appScreens: DownloadFile[] = [
  describe('/media/shaheen-money-app-iphone.png', { en: 'Home screen, iPhone (PNG)', ar: 'الشاشة الرئيسية، آيفون (PNG)' }),
  describe('/media/shaheen-money-app-android.png', { en: 'Home screen, Android (PNG)', ar: 'الشاشة الرئيسية، أندرويد (PNG)' }),
];

/**
 * The palette a designer may use. Kept in step with design/tokens.json.
 * `swatch` is a class rather than an inline style because the site's CSP
 * has no 'unsafe-inline' for styles, so a style="" attribute would simply
 * not paint (scripts/check-dist.mjs fails the build on one).
 */
export const brandColours: Array<{ name: string; hex: string; swatch: string; use: Localized }> = [
  {
    name: 'Navy',
    hex: '#071138',
    swatch: 'bg-navy-800',
    use: { en: 'The brand colour. Text on paper, the mark, bands of ink.', ar: 'لون العلامة. النصوص على الورق والشعار وأشرطة الحبر.' },
  },
  {
    name: 'Night',
    hex: '#060B1C',
    swatch: 'bg-night-900',
    use: { en: 'The digital world: the hero, how it works, the close.', ar: 'العالم الرقمي: الواجهة، وكيف بيشتغل، والختام.' },
  },
  {
    name: 'Paper',
    hex: '#F6F1E7',
    swatch: 'bg-paper-50',
    use: { en: 'The physical world: cash, receipts, every inner page.', ar: 'العالم الملموس: الكاش والإيصالات وكل الصفحات الداخلية.' },
  },
  {
    name: 'Signal',
    hex: '#00E1FF',
    swatch: 'bg-signal', // lint-allow signal-on-paper: the swatch is the colour itself
    use: { en: 'On Night only, sparingly: live motion, focus, the active route.', ar: 'على الليل فقط وبقلّة: الحركة والتركيز والمسار النشط.' },
  },
  {
    name: 'Signal ink',
    hex: '#006E86',
    swatch: 'bg-signal-ink',
    use: { en: 'The accent on Paper, where Signal would be unreadable.', ar: 'لون التمييز على الورق، حيث لا يُقرأ لون الإشارة.' },
  },
  {
    name: 'Amber',
    hex: '#F5A623',
    swatch: 'bg-amber',
    use: { en: 'Physical cash, on Night. On Paper, Amber ink (#8A5300).', ar: 'الكاش الملموس على الليل. وعلى الورق: الكهرماني الداكن (#8A5300).' },
  },
];

/**
 * The type, each shown in its own face: the specimen is set in the font it
 * names (`face` picks the class), in the script it is for.
 */
export const brandFonts: Array<{
  name: string;
  face: 'serif' | 'naskh' | 'sans' | 'plex' | 'mono';
  sample: string;
  sampleLang: 'en' | 'ar';
  use: Localized;
  licence: string;
}> = [
  {
    name: 'Instrument Serif',
    face: 'serif',
    sample: 'Shaheen Money',
    sampleLang: 'en',
    use: { en: 'Headlines, Latin. One italic word per headline.', ar: 'العناوين بالحروف اللاتينية، بكلمة مائلة واحدة في كل عنوان.' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'Noto Naskh Arabic',
    face: 'naskh',
    sample: 'شاهين موني',
    sampleLang: 'ar',
    use: { en: 'Headlines, Arabic (weight 500).', ar: 'العناوين بالعربية (وزن 500).' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'Instrument Sans',
    face: 'sans',
    sample: 'Shaheen Money',
    sampleLang: 'en',
    use: { en: 'Interface and body text, Latin.', ar: 'الواجهة والنصوص بالحروف اللاتينية.' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'IBM Plex Sans Arabic',
    face: 'plex',
    sample: 'شاهين موني',
    sampleLang: 'ar',
    use: { en: 'Interface and body text, Arabic.', ar: 'الواجهة والنصوص بالعربية.' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'Geist Mono',
    face: 'mono',
    sample: '0123456789',
    sampleLang: 'en',
    use: { en: 'Figures, codes, dates, coordinates and sources, in both languages.', ar: 'الأرقام والرموز والتواريخ والإحداثيات والمصادر، باللغتين.' },
    licence: 'https://openfontlicense.org/',
  },
];
