import { existsSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { Localized } from './types';

/**
 * MEDIA AND COMPANY DOCUMENTS — what a journalist, a partner or an investor
 * can download, and the brand files they must use instead of screenshotting
 * the site.
 *
 * Two rules, both enforced below at build time rather than by discipline:
 *
 *  1. A download that 404s on a press page is worse than no download, so a
 *     file listed here must exist in public/ or the build fails.
 *  2. Nothing is described from memory: size and last-modified date are read
 *     off the file itself, so they cannot go stale.
 *
 * To publish the pitch deck or the company profile, drop the PDF into
 * public/media/ and set `file` below. Until then the slot renders a
 * "content needed" marker in dev and nothing at all in production.
 */
export interface DownloadFile {
  /** Absolute site path, e.g. '/media/shaheen-falcon-navy.svg'. */
  file: string;
  label: Localized;
  /** Filled in by the build from the file on disk. */
  format: string;
  sizeKb: number;
}

export interface DownloadSlot {
  id: string;
  title: Localized;
  description: Localized;
  file: string | null;
}

// Resolved from the working directory, not from import.meta.url: this module
// is bundled into the server output at build time, so a path relative to the
// module would point into .vercel/output (same reason src/lib/og.ts reads
// node_modules from process.cwd()).
const publicDir = join(process.cwd(), 'public');

function describe(file: string, label: Localized): DownloadFile {
  const path = join(publicDir, file);
  // A path that climbs out of public/ would describe a file the site never
  // serves, and publish a link that 404s. Fail the build instead.
  if (!file.startsWith('/') || relative(publicDir, path).startsWith('..')) {
    throw new Error(`src/data/media.ts: "${file}" must be a site-absolute path inside public/.`);
  }
  if (!existsSync(path)) {
    throw new Error(
      `src/data/media.ts lists "${file}", which is not in public/. ` +
        `Run \`npm run media\` to regenerate the brand files, or remove the entry.`,
    );
  }
  return {
    file,
    label,
    format: (file.split('.').pop() ?? '').toUpperCase(),
    sizeKb: Math.max(1, Math.round(statSync(path).size / 1024)),
  };
}

export interface BrandAsset {
  id: string;
  name: Localized;
  note: Localized;
  /** Preview background, so a white mark is never shown on white. */
  preview: 'light' | 'dark';
  /** Preview the mark inside its circle, matching what the file contains. */
  circle?: boolean;
  files: DownloadFile[];
}

/** Generated by scripts/brand/build-media.mjs from the one vector master. */
export const brandAssets: BrandAsset[] = [
  {
    id: 'mark-navy',
    name: { en: 'Falcon mark, navy', ar: 'شعار الصقر، كحلي' },
    note: {
      en: 'For light backgrounds. The default mark.',
      ar: 'للخلفيات الفاتحة، وهو الشكل الأساسي للشعار.',
    },
    preview: 'light',
    files: [
      describe('/media/shaheen-falcon-navy.svg', { en: 'Vector', ar: 'ملف متجهي' }),
      describe('/media/shaheen-falcon-navy-1024.png', { en: 'PNG 1024px', ar: 'PNG 1024 بكسل' }),
      describe('/media/shaheen-falcon-navy-512.png', { en: 'PNG 512px', ar: 'PNG 512 بكسل' }),
    ],
  },
  {
    id: 'mark-white',
    name: { en: 'Falcon mark, white', ar: 'شعار الصقر، أبيض' },
    note: {
      en: 'For navy and photographic backgrounds only.',
      ar: 'للخلفيات الكحلية والصور فقط.',
    },
    preview: 'dark',
    files: [
      describe('/media/shaheen-falcon-white.svg', { en: 'Vector', ar: 'ملف متجهي' }),
      describe('/media/shaheen-falcon-white-1024.png', { en: 'PNG 1024px', ar: 'PNG 1024 بكسل' }),
      describe('/media/shaheen-falcon-white-512.png', { en: 'PNG 512px', ar: 'PNG 512 بكسل' }),
    ],
  },
  {
    id: 'tile',
    circle: true,
    name: { en: 'Circle lockup', ar: 'الشعار داخل الدائرة' },
    note: {
      en: 'The mark in its circle, as the site and the app icon use it.',
      ar: 'الشعار داخل دائرته، كما يستخدمه الموقع وأيقونة التطبيق.',
    },
    preview: 'light',
    files: [
      describe('/media/shaheen-falcon-tile-navy.svg', { en: 'Navy circle', ar: 'دائرة كحلية' }),
      describe('/media/shaheen-falcon-tile-white.svg', { en: 'White circle', ar: 'دائرة بيضاء' }),
      describe('/icon-512.png', { en: 'App icon, PNG 512px', ar: 'أيقونة التطبيق، PNG 512 بكسل' }),
    ],
  },
];

/**
 * Documents the company still has to supply. Set `file` to a path under
 * public/ once the PDF exists; the build then reads its size and date.
 */
export const documentSlots: DownloadSlot[] = [
  {
    id: 'pitch-deck',
    title: { en: 'Pitch deck', ar: 'العرض التقديمي' },
    description: {
      en: 'What we are building, the market, the network and where we are going.',
      ar: 'ما الذي نبنيه، والسوق، والشبكة، وإلى أين نتجه.',
    },
    file: null,
  },
  {
    id: 'company-profile',
    title: { en: 'Company profile', ar: 'الملف التعريفي للشركة' },
    description: {
      en: 'The company, its history, its people and how to reach us.',
      ar: 'الشركة وتاريخها وفريقها وطريقة التواصل معنا.',
    },
    file: null,
  },
  {
    id: 'brand-guidelines',
    title: { en: 'Brand guidelines', ar: 'دليل الهوية البصرية' },
    description: {
      en: 'Clear space, minimum sizes, colour and typography in full.',
      ar: 'المساحة الحرة والأحجام الدنيا والألوان والخطوط بالتفصيل.',
    },
    file: null,
  },
];

export const resolvedDocuments = documentSlots.map((slot) => ({
  ...slot,
  download: slot.file ? describe(slot.file, slot.title) : null,
}));

/**
 * The palette a designer may use. Kept in step with design/tokens.json.
 * `swatch` is a class rather than an inline style because the site's CSP
 * has no 'unsafe-inline' for styles, so a style="" attribute would simply
 * not paint (scripts/check-dist.mjs fails the build on one).
 */
export const brandColours: Array<{ name: string; hex: string; swatch: string; use: Localized }> = [
  {
    name: 'Navy',
    hex: '#071138',
    swatch: 'bg-navy',
    use: { en: 'Primary. Text, dark surfaces, the mark.', ar: 'اللون الأساسي. النصوص والأسطح الداكنة والشعار.' },
  },
  {
    name: 'Blue',
    hex: '#1400FF',
    swatch: 'bg-blue',
    use: { en: 'Primary actions on light surfaces. Never on navy.', ar: 'الإجراءات الأساسية على الأسطح الفاتحة، ولا تُستخدم على الكحلي.' },
  },
  {
    name: 'Cyan',
    hex: '#00E1FF',
    swatch: 'bg-cyan',
    use: { en: 'Accents on dark surfaces only.', ar: 'لمسات على الأسطح الداكنة فقط.' },
  },
  {
    name: 'White',
    hex: '#FFFFFF',
    swatch: 'bg-white',
    use: { en: 'Light surfaces and the mark on navy.', ar: 'الأسطح الفاتحة والشعار على الكحلي.' },
  },
];

export const brandFonts: Array<{ name: string; use: Localized; licence: string }> = [
  {
    name: 'Instrument Sans',
    use: { en: 'Headings, Latin.', ar: 'العناوين، بالحروف اللاتينية.' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'Inter',
    use: { en: 'Body text and figures, Latin.', ar: 'النصوص والأرقام، بالحروف اللاتينية.' },
    licence: 'https://openfontlicense.org/',
  },
  {
    name: 'IBM Plex Sans Arabic',
    use: { en: 'Everything in Arabic.', ar: 'كل النصوص العربية.' },
    licence: 'https://openfontlicense.org/',
  },
];
